require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-disable_syntax

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

# https://github.com/fatkodima/rubocop-disable_syntax
Style/DisableSyntax:
  DisableSyntax:
    - unless
    - and_or_not

Style/NegatedIf:
  Enabled: false
