name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build with Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.2']

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Start Sidekiq
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: pwd && bundle exec sidekiq -c 2 -r ./spec/support/jobs/*.rb &
      - name: Run the default task
        run: bundle exec rake
